### ISSUE TITLE
Wrong parameter -Vendor in Example for "Add-AddRemovePrograms"

### ISSUE THREAD

**Issue by OliverGebhardt** [ceterion/PackagingFramework#1]
In all 3 Examples for the function "Add-AddRemovePrograms" the parameter -Vendor has to be changed to -Publisher (or Alias('Vendor') has to be added in the parameterlist of the function).

**Comment by AndreasMariotti** [comment]
I can confirm this documentation bug. The correct parameter name is -Publisher and not -Vendor like shown in the online help. This documentation bug will be fixed in the next version.

**Comment by JensMiltenberger** [comment]
fixed

**Comment by JensMiltenberger** [comment]
fyi - already fixed in version 1.0.18
